from pydantic import BaseModel
from typing import List, Optional

class AnalyzeRequest(BaseModel):
    fileId: str
    fileName: str
    workflowType: Optional[str] = "Contract Analysis"

class AnalyzeResponseData(BaseModel):
    analysisId: str
    fileName: str
    workflowType: str
    status: str = "Completed"
    confidence: int = 95
    summary: str = "Placeholder analysis output generated by backend engine."
    suggestedActions: List[str] = [
        "Review extracted document metadata",
        "Verify operational policy compliance"
    ]
